export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/img-1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Best Shirt",
      category: "Shirts",
      image: "/images/img-2.jpg",
      price: 40,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
    },
    {
      _id: "3",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/img-3.jpg",
      price: 70,
      brand: "Nike",
      rating: 4,
      numReviews: 12,
    },
    {
      _id: "4",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/img-1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
